name: pick
favicon: null
layout_spectrum: 0.8815077270846814
typography_spectrum: 0.5934301903471351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7775776195339859
  lightness: 0.7978091407567263
  saturation: 0.6522486647590995
  rhythmicContrast: 0.051491788355633616
purpose: []
